#import <Foundation/Foundation.h>
#import "SWGAccountingJournalPage.h"
#import "SWGEditAccountingJournal.h"
#import "SWGNewAccountingJournal.h"
#import "SWGApi.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGAccountingJournalsApi: NSObject <SWGApi>

extern NSString* kSWGAccountingJournalsApiErrorDomain;
extern NSInteger kSWGAccountingJournalsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Agregar póliza contable
/// 
///
/// @param varNewAccountingJournal 
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) accountingJournalsAddAccountingJournalWithVarNewAccountingJournal: (SWGNewAccountingJournal*) varNewAccountingJournal
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Eliminar póliza contable
/// 
///
/// @param idList 
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) accountingJournalsDeleteAccountingJournalWithIdList: (NSArray<NSString*>*) idList
    completionHandler: (void (^)(NSError* error)) handler;


/// Editar póliza contable
/// 
///
/// @param accountingJournal 
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) accountingJournalsEditAccountingJournalWithAccountingJournal: (SWGEditAccountingJournal*) accountingJournal
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Obtiene la lista de pólizas contables.
/// 
///
/// @param filter Filters the results, based on a Boolean condition. (optional)
/// @param orderby Sorts the results. (optional)
/// @param top Returns only the first n results. (optional)
/// @param skip Skips the first n results. (optional)
/// 
///  code:200 message:"OK"
///
/// @return SWGAccountingJournalPage*
-(NSURLSessionTask*) accountingJournalsGetWithFilter: (NSString*) filter
    orderby: (NSString*) orderby
    top: (NSNumber*) top
    skip: (NSNumber*) skip
    completionHandler: (void (^)(SWGAccountingJournalPage* output, NSError* error)) handler;



@end
