#import <Foundation/Foundation.h>
#import "SWGNewActivity.h"
#import "SWGApi.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGActivitiesApi: NSObject <SWGApi>

extern NSString* kSWGActivitiesApiErrorDomain;
extern NSInteger kSWGActivitiesApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Agregar actividad
/// 
///
/// @param varNewActivity 
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) activitiesAddActivityWithVarNewActivity: (SWGNewActivity*) varNewActivity
    completionHandler: (void (^)(NSError* error)) handler;



@end
