#import <Foundation/Foundation.h>
#import "SWGCommentPage.h"
#import "SWGNewComment.h"
#import "SWGApi.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGCommentsApi: NSObject <SWGApi>

extern NSString* kSWGCommentsApiErrorDomain;
extern NSInteger kSWGCommentsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Agregar comentario
/// 
///
/// @param varNewComment 
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) commentsAddCommentWithVarNewComment: (SWGNewComment*) varNewComment
    completionHandler: (void (^)(NSError* error)) handler;


/// Listar comentarios por external ID
/// 
///
/// @param filter Filters the results, based on a Boolean condition. (optional)
/// @param orderby Sorts the results. (optional)
/// @param top Returns only the first n results. (optional)
/// @param skip Skips the first n results. (optional)
/// 
///  code:200 message:"OK"
///
/// @return SWGCommentPage*
-(NSURLSessionTask*) commentsGetWithFilter: (NSString*) filter
    orderby: (NSString*) orderby
    top: (NSNumber*) top
    skip: (NSNumber*) skip
    completionHandler: (void (^)(SWGCommentPage* output, NSError* error)) handler;



@end
