#import <Foundation/Foundation.h>
#import "SWGClientDetails.h"
#import "SWGClientListItemPage.h"
#import "SWGEditClient.h"
#import "SWGNewClient.h"
#import "SWGApi.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGClientsApi: NSObject <SWGApi>

extern NSString* kSWGClientsApiErrorDomain;
extern NSInteger kSWGClientsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Agregar Cliente
/// 
///
/// @param varNewClient 
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) clientsAddClientWithVarNewClient: (SWGNewClient*) varNewClient
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Borrar Cliente
/// 
///
/// @param _id 
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) clientsDeleteByIDWithId: (NSString*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// Editar Cliente
/// 
///
/// @param client 
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) clientsEditClientWithClient: (SWGEditClient*) client
    completionHandler: (void (^)(NSError* error)) handler;


/// Obtiene la lista de clientes.
/// El filtro es opcional
///
/// @param filter Filters the results, based on a Boolean condition. (optional)
/// @param orderby Sorts the results. (optional)
/// @param top Returns only the first n results. (optional)
/// @param skip Skips the first n results. (optional)
/// 
///  code:200 message:"OK"
///
/// @return SWGClientListItemPage*
-(NSURLSessionTask*) clientsGetWithFilter: (NSString*) filter
    orderby: (NSString*) orderby
    top: (NSNumber*) top
    skip: (NSNumber*) skip
    completionHandler: (void (^)(SWGClientListItemPage* output, NSError* error)) handler;


/// Obtiene los detalles de un cliente.
/// 
///
/// @param _id 
/// 
///  code:200 message:"OK"
///
/// @return SWGClientDetails*
-(NSURLSessionTask*) clientsGetDetailsWithId: (NSString*) _id
    completionHandler: (void (^)(SWGClientDetails* output, NSError* error)) handler;



@end
