#import <Foundation/Foundation.h>
#import "SWGInvoiceDetails.h"
#import "SWGInvoiceListItemPage.h"
#import "SWGNewInvoice.h"
#import "SWGNewPayment.h"
#import "SWGApi.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGInvoicesApi: NSObject <SWGApi>

extern NSString* kSWGInvoicesApiErrorDomain;
extern NSInteger kSWGInvoicesApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Agregar Venta
/// 
///
/// @param varNewInvoice 
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) invoicesAddInvoiceWithVarNewInvoice: (SWGNewInvoice*) varNewInvoice
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Registrar pago a venta
/// 
///
/// @param varNewPayment 
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) invoicesAddPaymentWithVarNewPayment: (SWGNewPayment*) varNewPayment
    completionHandler: (void (^)(NSError* error)) handler;


/// Eliminar factura
/// 
///
/// @param _id ID
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) invoicesDeleteInvoiceWithId: (NSString*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// Obtiene la lista de ventas.
/// El filtro es opcional
///
/// @param filter Filters the results, based on a Boolean condition. (optional)
/// @param orderby Sorts the results. (optional)
/// @param top Returns only the first n results. (optional)
/// @param skip Skips the first n results. (optional)
/// 
///  code:200 message:"OK"
///
/// @return SWGInvoiceListItemPage*
-(NSURLSessionTask*) invoicesGetWithFilter: (NSString*) filter
    orderby: (NSString*) orderby
    top: (NSNumber*) top
    skip: (NSNumber*) skip
    completionHandler: (void (^)(SWGInvoiceListItemPage* output, NSError* error)) handler;


/// Obtiene los detalles de una venta por número
/// 
///
/// @param idOrNumber 
/// 
///  code:200 message:"OK"
///
/// @return SWGInvoiceDetails*
-(NSURLSessionTask*) invoicesGetByNumberWithIdOrNumber: (NSString*) idOrNumber
    completionHandler: (void (^)(SWGInvoiceDetails* output, NSError* error)) handler;


/// Obtener el PDF de una venta
/// 
///
/// @param _id ID
/// 
///  code:200 message:"File Response"
///
/// @return NSURL*
-(NSURLSessionTask*) invoicesGetPDFWithId: (NSString*) _id
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Obtener el XML de una venta
/// 
///
/// @param _id ID
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) invoicesGetXMLWithId: (NSString*) _id
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;



@end
