#import <Foundation/Foundation.h>
#import "SWGInventorytPage.h"
#import "SWGNewInventoryAdjustment.h"
#import "SWGApi.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGInventoryApi: NSObject <SWGApi>

extern NSString* kSWGInventoryApiErrorDomain;
extern NSInteger kSWGInventoryApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Agregar ajuste de inventario.
/// 
///
/// @param varNewAdjustment 
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) inventoryAddInventoryAdjustmentWithVarNewAdjustment: (SWGNewInventoryAdjustment*) varNewAdjustment
    completionHandler: (void (^)(NSError* error)) handler;


/// Obtener inventario por almacén.
/// 
///
/// @param warehouseID 
/// @param filter Filters the results, based on a Boolean condition. (optional)
/// @param orderby Sorts the results. (optional)
/// @param top Returns only the first n results. (optional)
/// @param skip Skips the first n results. (optional)
/// 
///  code:200 message:"OK"
///
/// @return SWGInventorytPage*
-(NSURLSessionTask*) inventoryGetInventoryByWarehouseIDWithWarehouseID: (NSString*) warehouseID
    filter: (NSString*) filter
    orderby: (NSString*) orderby
    top: (NSNumber*) top
    skip: (NSNumber*) skip
    completionHandler: (void (^)(SWGInventorytPage* output, NSError* error)) handler;



@end
