#import <Foundation/Foundation.h>
#import "SWGInvoiceDetails.h"
#import "SWGNewInvoice.h"
#import "SWGNewPayment.h"
#import "SWGApi.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGInvoicesApi: NSObject <SWGApi>

extern NSString* kSWGInvoicesApiErrorDomain;
extern NSInteger kSWGInvoicesApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Agregar factura
/// 
///
/// @param varNewInvoice 
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) invoicesAddInvoiceWithVarNewInvoice: (SWGNewInvoice*) varNewInvoice
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Registrar pago a factura
/// 
///
/// @param varNewPayment 
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) invoicesAddPaymentWithVarNewPayment: (SWGNewPayment*) varNewPayment
    completionHandler: (void (^)(NSError* error)) handler;


/// Eliminar factura
/// 
///
/// @param _id ID
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) invoicesDeleteInvoiceWithId: (NSString*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// Obtiene los detalles de una venta
/// 
///
/// @param _id ID
/// 
///  code:200 message:"OK"
///
/// @return SWGInvoiceDetails*
-(NSURLSessionTask*) invoicesGetByIDWithId: (NSString*) _id
    completionHandler: (void (^)(SWGInvoiceDetails* output, NSError* error)) handler;


/// Obtiene los detalles de una venta
/// 
///
/// @param number Serie y Número
/// 
///  code:200 message:"OK"
///
/// @return SWGInvoiceDetails*
-(NSURLSessionTask*) invoicesGetByNumberWithNumber: (NSString*) number
    completionHandler: (void (^)(SWGInvoiceDetails* output, NSError* error)) handler;


/// Obtener el PDF de una venta
/// 
///
/// @param _id ID
/// 
///  code:200 message:"OK"
///
/// @return NSObject*
-(NSURLSessionTask*) invoicesGetPDFWithId: (NSString*) _id
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Obtener el XML de una venta
/// 
///
/// @param _id ID
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) invoicesGetXMLWithId: (NSString*) _id
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;



@end
