#import <Foundation/Foundation.h>
#import "SWGEditOrder.h"
#import "SWGNewOrder.h"
#import "SWGOrderDetails.h"
#import "SWGApi.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGOrdersApi: NSObject <SWGApi>

extern NSString* kSWGOrdersApiErrorDomain;
extern NSInteger kSWGOrdersApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Agregar pedido
/// 
///
/// @param varNewOrder 
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) ordersAddOrderWithVarNewOrder: (SWGNewOrder*) varNewOrder
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Eliminar pedido
/// 
///
/// @param _id ID
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) ordersDeleteOrderWithId: (NSString*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// Editar pedido
/// 
///
/// @param order 
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) ordersEditOrderWithOrder: (SWGEditOrder*) order
    completionHandler: (void (^)(NSError* error)) handler;


/// Obtiene los detalles de un pedido
/// 
///
/// @param _id ID
/// 
///  code:200 message:"OK"
///
/// @return SWGOrderDetails*
-(NSURLSessionTask*) ordersGetByIDWithId: (NSString*) _id
    completionHandler: (void (^)(SWGOrderDetails* output, NSError* error)) handler;



@end
