#import <Foundation/Foundation.h>
#import "SWGEditService.h"
#import "SWGNewService.h"
#import "SWGServicesPage.h"
#import "SWGApi.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGServicesApi: NSObject <SWGApi>

extern NSString* kSWGServicesApiErrorDomain;
extern NSInteger kSWGServicesApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Agregar Concepto de Venta
/// 
///
/// @param varNewService 
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) servicesAddProductWithVarNewService: (SWGNewService*) varNewService
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Borrar Servicio
/// 
///
/// @param _id 
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) servicesDeleteByIDWithId: (NSString*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// Editar Concepto de Venta
/// 
///
/// @param service 
/// 
///  code:204 message:"No Content"
///
/// @return void
-(NSURLSessionTask*) servicesEditProductWithService: (SWGEditService*) service
    completionHandler: (void (^)(NSError* error)) handler;


/// Obtiene la lista de conceptos de venta.
/// El filtro es opcional
///
/// @param filter Filters the results, based on a Boolean condition. (optional)
/// @param orderby Sorts the results. (optional)
/// @param top Returns only the first n results. (optional)
/// @param skip Skips the first n results. (optional)
/// 
///  code:200 message:"OK"
///
/// @return SWGServicesPage*
-(NSURLSessionTask*) servicesGetServicesWithFilter: (NSString*) filter
    orderby: (NSString*) orderby
    top: (NSNumber*) top
    skip: (NSNumber*) skip
    completionHandler: (void (^)(SWGServicesPage* output, NSError* error)) handler;



@end
