#import <Foundation/Foundation.h>
#import "SWGUserProfile.h"
#import "SWGApi.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGUserProfileApi: NSObject <SWGApi>

extern NSString* kSWGUserProfileApiErrorDomain;
extern NSInteger kSWGUserProfileApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Obtiene la lista de cuentas contables.
/// 
///
/// 
///  code:200 message:"OK"
///
/// @return SWGUserProfile*
-(NSURLSessionTask*) userProfileGetWithCompletionHandler: 
    (void (^)(SWGUserProfile* output, NSError* error)) handler;



@end
