#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGAccountingJournalItem
@end

@interface SWGAccountingJournalItem : SWGObject


@property(nonatomic) NSString* accountID;

@property(nonatomic) NSString* accountName;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSNumber* debit;

@property(nonatomic) NSNumber* charge;

@end
