#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGAccount
@end

@interface SWGAccount : SWGObject


@property(nonatomic) NSString* _iD;

@property(nonatomic) NSString* gLGroup;

@property(nonatomic) NSString* group;

@property(nonatomic) NSString* subGroup;

@property(nonatomic) NSString* gLGroupID;

@property(nonatomic) NSString* groupID;

@property(nonatomic) NSString* subGroupID;

@property(nonatomic) NSString* number;

@property(nonatomic) NSString* _description;

@end
