#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGAccountingJournalItem.h"
@protocol SWGAccountingJournalItem;
@class SWGAccountingJournalItem;



@protocol SWGAccountingJournal
@end

@interface SWGAccountingJournal : SWGObject


@property(nonatomic) NSString* _iD;

@property(nonatomic) NSString* documentID;

@property(nonatomic) NSString* type;

@property(nonatomic) NSDate* applicationDate;

@property(nonatomic) NSDate* creationDate;

@property(nonatomic) NSNumber* number;

@property(nonatomic) NSString* locationID;

@property(nonatomic) NSString* periodType;

@property(nonatomic) NSArray<SWGAccountingJournalItem>* items;

@end
