#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGGLGroup.h"
@protocol SWGGLGroup;
@class SWGGLGroup;



@protocol SWGAccountCategories
@end

@interface SWGAccountCategories : SWGObject


@property(nonatomic) NSArray<SWGGLGroup>* gLGroups;

@end
