#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGBankAccount
@end

@interface SWGBankAccount : SWGObject


@property(nonatomic) NSString* _iD;

@property(nonatomic) NSNumber* type;

@property(nonatomic) NSString* typeText;

@property(nonatomic) NSString* bankID;

@property(nonatomic) NSString* bankName;

@property(nonatomic) NSString* name;

@property(nonatomic) NSNumber* balance;

@property(nonatomic) NSString* currencyID;

@property(nonatomic) NSString* currencyCode;

@end
