#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGBankAccount.h"
@protocol SWGBankAccount;
@class SWGBankAccount;



@protocol SWGBankAccountPage
@end

@interface SWGBankAccountPage : SWGObject


@property(nonatomic) NSArray<SWGBankAccount>* value;

@property(nonatomic) NSString* nextLink;

@property(nonatomic) NSNumber* count;

@end
