#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGCategory2.h"
@protocol SWGCategory2;
@class SWGCategory2;



@protocol SWGCategory1
@end

@interface SWGCategory1 : SWGObject


@property(nonatomic) NSString* _iD;

@property(nonatomic) NSString* name;

@property(nonatomic) NSArray<SWGCategory2>* subCategories;

@end
