#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGEditProspect
@end

@interface SWGEditProspect : SWGObject


@property(nonatomic) NSString* name;

@property(nonatomic) NSString* _iD;

@property(nonatomic) NSString* comments;

@property(nonatomic) NSString* company;

@property(nonatomic) NSString* email;

@property(nonatomic) NSNumber* isPublic;

@property(nonatomic) NSString* phone;

@property(nonatomic) NSString* phoneExt;

@end
