#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGEditService
@end

@interface SWGEditService : SWGObject


@property(nonatomic) NSString* _iD;

@property(nonatomic) NSString* code;

@property(nonatomic) NSString* title;

@property(nonatomic) NSString* currencyID;

@property(nonatomic) NSString* sATCompanyAccountID;

@property(nonatomic) NSString* measurementUnit;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSString* category1ID;

@property(nonatomic) NSString* category2ID;

@property(nonatomic) NSString* category3ID;

@property(nonatomic) NSNumber* variableConcept;

@property(nonatomic) NSNumber* chargeVAT;

@end
