#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGIEdmTypeReference.h"
#import "SWGRangeVariable.h"
#import "SWGSingleValueNode.h"
@protocol SWGIEdmTypeReference;
@class SWGIEdmTypeReference;
@protocol SWGRangeVariable;
@class SWGRangeVariable;
@protocol SWGSingleValueNode;
@class SWGSingleValueNode;



@protocol SWGFilterClause
@end

@interface SWGFilterClause : SWGObject


@property(nonatomic) SWGSingleValueNode* expression;

@property(nonatomic) SWGRangeVariable* rangeVariable;

@property(nonatomic) SWGIEdmTypeReference* itemType;

@end
