#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGGroup.h"
@protocol SWGGroup;
@class SWGGroup;



@protocol SWGGLGroup
@end

@interface SWGGLGroup : SWGObject


@property(nonatomic) NSString* _iD;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSArray<SWGGroup>* groups;

@end
