#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGIEdmType.h"
@protocol SWGIEdmType;
@class SWGIEdmType;



@protocol SWGIEdmTypeReference
@end

@interface SWGIEdmTypeReference : SWGObject


@property(nonatomic) NSNumber* isNullable;

@property(nonatomic) SWGIEdmType* definition;

@end
