#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGIEdmTerm.h"
#import "SWGIEdmVocabularyAnnotatable.h"
@protocol SWGIEdmTerm;
@class SWGIEdmTerm;
@protocol SWGIEdmVocabularyAnnotatable;
@class SWGIEdmVocabularyAnnotatable;



@protocol SWGIEdmVocabularyAnnotation
@end

@interface SWGIEdmVocabularyAnnotation : SWGObject


@property(nonatomic) NSString* qualifier;

@property(nonatomic) SWGIEdmTerm* term;

@property(nonatomic) SWGIEdmVocabularyAnnotatable* target;

@end
