#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGInvoiceDetailsProduct.h"
#import "SWGInvoiceDetailsService.h"
@protocol SWGInvoiceDetailsProduct;
@class SWGInvoiceDetailsProduct;
@protocol SWGInvoiceDetailsService;
@class SWGInvoiceDetailsService;



@protocol SWGInvoiceDetails
@end

@interface SWGInvoiceDetails : SWGObject


@property(nonatomic) NSString* _iD;

@property(nonatomic) NSString* uUID;

@property(nonatomic) NSString* series;

@property(nonatomic) NSNumber* number;

@property(nonatomic) NSString* clientID;

@property(nonatomic) NSString* clientName;

@property(nonatomic) NSNumber* paymentTerms;

@property(nonatomic) NSString* status;

@property(nonatomic) NSNumber* statusCode;

@property(nonatomic) NSString* clientPhoneNumber;

@property(nonatomic) NSString* clientContact;

@property(nonatomic) NSString* rFC;

@property(nonatomic) NSString* createdByID;

@property(nonatomic) NSString* createdByName;

@property(nonatomic) NSDate* creationDate;

@property(nonatomic) NSDate* applicationDate;

@property(nonatomic) NSString* priceListID;

@property(nonatomic) NSString* priceListName;

@property(nonatomic) NSString* locationID;

@property(nonatomic) NSString* locationName;

@property(nonatomic) NSString* warehouseID;

@property(nonatomic) NSString* warehouseName;

@property(nonatomic) NSString* cFDIPaymentMethod;

@property(nonatomic) NSString* cFDIPaymentTerm;

@property(nonatomic) NSString* cFDIAccountNumber;

@property(nonatomic) NSString* currencyName;

@property(nonatomic) NSNumber* exchangeRate;

@property(nonatomic) NSString* purchaseOrder;

@property(nonatomic) NSString* fiscalID;

@property(nonatomic) NSString* address;

@property(nonatomic) NSString* comments;

@property(nonatomic) NSNumber* subtotal;

@property(nonatomic) NSNumber* discount;

@property(nonatomic) NSNumber* vAT;

@property(nonatomic) NSNumber* iEPS;

@property(nonatomic) NSNumber* vATRet;

@property(nonatomic) NSNumber* iSRRet;

@property(nonatomic) NSNumber* payments;

@property(nonatomic) NSNumber* creditNotes;

@property(nonatomic) NSArray<SWGInvoiceDetailsProduct>* products;

@property(nonatomic) NSArray<SWGInvoiceDetailsService>* services;

@end
