#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGInvoiceListItem
@end

@interface SWGInvoiceListItem : SWGObject


@property(nonatomic) NSString* serie;

@property(nonatomic) NSDate* date;

@property(nonatomic) NSNumber* number;

@property(nonatomic) NSString* uUID;

@property(nonatomic) NSDate* expirationDate;

@property(nonatomic) NSString* clientID;

@property(nonatomic) NSString* clientName;

@property(nonatomic) NSString* rFC;

@property(nonatomic) NSNumber* cost;

@property(nonatomic) NSNumber* subtotal;

@property(nonatomic) NSNumber* discount;

@property(nonatomic) NSNumber* vAT;

@property(nonatomic) NSNumber* iEPS;

@property(nonatomic) NSNumber* iSRRet;

@property(nonatomic) NSNumber* vATRet;

@property(nonatomic) NSNumber* total;

@property(nonatomic) NSNumber* payments;

@property(nonatomic) NSNumber* creditNotes;

@property(nonatomic) NSString* currencyID;

@property(nonatomic) NSString* locationID;

@property(nonatomic) NSString* warehouseID;

@property(nonatomic) NSString* priceListID;

@property(nonatomic) NSString* cFDIID;

@property(nonatomic) NSNumber* cFDIUse;

@property(nonatomic) NSNumber* exchangeRate;

@property(nonatomic) NSNumber* vATRetRate;

@property(nonatomic) NSString* comments;

@property(nonatomic) NSNumber* vATRate;

@property(nonatomic) NSString* purchaseOrder;

@property(nonatomic) NSNumber* isFiscalInvoice;

@property(nonatomic) NSNumber* showIEPS;

@property(nonatomic) NSNumber* status;

@end
