#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGNewPayment
@end

@interface SWGNewPayment : SWGObject


@property(nonatomic) NSString* invoiceID;

@property(nonatomic) NSString* accountID;

@property(nonatomic) NSDate* date;

@property(nonatomic) NSString* reference;

@property(nonatomic) NSNumber* amount;

@property(nonatomic) NSNumber* paymentTerm;

@property(nonatomic) NSString* comments;

@property(nonatomic) NSNumber* exchangeRate;

@property(nonatomic) NSNumber* exchangeRateAccount;

@end
