#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGNewActivity
@end

@interface SWGNewActivity : SWGObject


@property(nonatomic) NSString* comment;

@property(nonatomic) NSDate* startDate;

@property(nonatomic) NSDate* endDate;

@property(nonatomic) NSString* eventType;

@property(nonatomic) NSNumber* isPublic;

@property(nonatomic) NSString* title;

@property(nonatomic) NSNumber* repeatable;

@property(nonatomic) NSNumber* repeatInterval;

@property(nonatomic) NSNumber* repeatType;

@property(nonatomic) NSNumber* repetitions;

@property(nonatomic) NSString* externalID;

@property(nonatomic) NSNumber* externalIDType;

@end
