#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGNewWebHookSubscription
@end

@interface SWGNewWebHookSubscription : SWGObject


@property(nonatomic) NSString* event;

@property(nonatomic) NSString* targetUrl;

@end
