#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGNewAccountingJournalItem
@end

@interface SWGNewAccountingJournalItem : SWGObject


@property(nonatomic) NSString* sATCompanyAccountID;

@property(nonatomic) NSNumber* cargo;

@property(nonatomic) NSNumber* abono;

@property(nonatomic) NSString* comments;

@end
