#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGNewAccountingJournalItem.h"
@protocol SWGNewAccountingJournalItem;
@class SWGNewAccountingJournalItem;



@protocol SWGNewAccountingJournal
@end

@interface SWGNewAccountingJournal : SWGObject


@property(nonatomic) NSDate* date;

@property(nonatomic) NSString* comments;

@property(nonatomic) NSString* locationID;

@property(nonatomic) NSArray<SWGNewAccountingJournalItem>* journalItems;

@end
