#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGNewInvoicePayment
@end

@interface SWGNewInvoicePayment : SWGObject


@property(nonatomic) NSNumber* paymentMethod;

@property(nonatomic) NSString* accountID;

@property(nonatomic) NSNumber* amount;

@property(nonatomic) NSNumber* exchangeRate;

@property(nonatomic) NSNumber* exchangeRateAccount;

@property(nonatomic) NSString* reference;

@end
