#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGIEdmModel.h"
#import "SWGIEdmType.h"
@protocol SWGIEdmModel;
@class SWGIEdmModel;
@protocol SWGIEdmType;
@class SWGIEdmType;



@protocol SWGODataQueryContext
@end

@interface SWGODataQueryContext : SWGObject


@property(nonatomic) SWGIEdmModel* model;

@property(nonatomic) SWGIEdmType* elementType;

@property(nonatomic) NSString* elementClrType;

@end
