#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGOrderDetailsProduct.h"
#import "SWGOrderDetailsService.h"
@protocol SWGOrderDetailsProduct;
@class SWGOrderDetailsProduct;
@protocol SWGOrderDetailsService;
@class SWGOrderDetailsService;



@protocol SWGOrderDetails
@end

@interface SWGOrderDetails : SWGObject


@property(nonatomic) NSString* _iD;

@property(nonatomic) NSString* clientID;

@property(nonatomic) NSString* clientName;

@property(nonatomic) NSString* priceListName;

@property(nonatomic) NSString* priceListID;

@property(nonatomic) NSString* locationName;

@property(nonatomic) NSString* locationID;

@property(nonatomic) NSString* warehouseID;

@property(nonatomic) NSString* warehouseName;

@property(nonatomic) NSDate* orderDate;

@property(nonatomic) NSString* comments;

@property(nonatomic) NSNumber* number;

@property(nonatomic) NSString* address;

@property(nonatomic) NSString* clientContact;

@property(nonatomic) NSString* phoneNumber;

@property(nonatomic) NSString* employeeName;

@property(nonatomic) NSString* employeeID;

@property(nonatomic) NSNumber* statusCode;

@property(nonatomic) NSString* purchaseOrder;

@property(nonatomic) NSString* status;

@property(nonatomic) NSString* currencyName;

@property(nonatomic) NSString* currencyID;

@property(nonatomic) NSNumber* exchangeRate;

@property(nonatomic) NSString* rFC;

@property(nonatomic) NSNumber* serviceSubtotal;

@property(nonatomic) NSNumber* productSubtotal;

@property(nonatomic) NSNumber* discount;

@property(nonatomic) NSNumber* vATRate;

@property(nonatomic) NSNumber* vAT;

@property(nonatomic) NSNumber* discountType;

@property(nonatomic) NSNumber* iEPS;

@property(nonatomic) NSNumber* iEPSRATE;

@property(nonatomic) NSNumber* iSRRet;

@property(nonatomic) NSNumber* iSRRetRate;

@property(nonatomic) NSNumber* vatRet;

@property(nonatomic) NSNumber* vatRetRate;

@property(nonatomic) NSNumber* total;

@property(nonatomic) NSArray<SWGOrderDetailsProduct>* products;

@property(nonatomic) NSArray<SWGOrderDetailsService>* services;

@end
