#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGODataQueryContext.h"
#import "SWGOrderByClause.h"
#import "SWGOrderByNode.h"
#import "SWGOrderByQueryValidator.h"
@protocol SWGODataQueryContext;
@class SWGODataQueryContext;
@protocol SWGOrderByClause;
@class SWGOrderByClause;
@protocol SWGOrderByNode;
@class SWGOrderByNode;
@protocol SWGOrderByQueryValidator;
@class SWGOrderByQueryValidator;



@protocol SWGOrderByQueryOption
@end

@interface SWGOrderByQueryOption : SWGObject


@property(nonatomic) SWGODataQueryContext* context;

@property(nonatomic) NSArray<SWGOrderByNode>* orderByNodes;

@property(nonatomic) NSString* rawValue;

@property(nonatomic) SWGOrderByQueryValidator* validator;

@property(nonatomic) SWGOrderByClause* orderByClause;

@end
