#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGProductPricesItems
@end

@interface SWGProductPricesItems : SWGObject


@property(nonatomic) NSString* name;

@property(nonatomic) NSNumber* margin;

@property(nonatomic) NSNumber* price;

@property(nonatomic) NSString* currencyCode;

@property(nonatomic) NSNumber* type;

@end
