#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGProductInventories
@end

@interface SWGProductInventories : SWGObject


@property(nonatomic) NSString* warehouseName;

@property(nonatomic) NSNumber* min;

@property(nonatomic) NSNumber* max;

@property(nonatomic) NSString* location;

@property(nonatomic) NSNumber* visible;

@property(nonatomic) NSNumber* inventory;

@end
