#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGProviderListItem.h"
@protocol SWGProviderListItem;
@class SWGProviderListItem;



@protocol SWGProviderListItemPage
@end

@interface SWGProviderListItemPage : SWGObject


@property(nonatomic) NSArray<SWGProviderListItem>* value;

@property(nonatomic) NSString* nextLink;

@property(nonatomic) NSNumber* count;

@end
