#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Bind ERP API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGODataQueryContext.h"
#import "SWGSelectExpandClause.h"
#import "SWGSelectExpandQueryValidator.h"
@protocol SWGODataQueryContext;
@class SWGODataQueryContext;
@protocol SWGSelectExpandClause;
@class SWGSelectExpandClause;
@protocol SWGSelectExpandQueryValidator;
@class SWGSelectExpandQueryValidator;



@protocol SWGSelectExpandQueryOption
@end

@interface SWGSelectExpandQueryOption : SWGObject


@property(nonatomic) SWGODataQueryContext* context;

@property(nonatomic) NSString* rawSelect;

@property(nonatomic) NSString* rawExpand;

@property(nonatomic) SWGSelectExpandQueryValidator* validator;

@property(nonatomic) SWGSelectExpandClause* selectExpandClause;

@end
